apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: jenkins
  namespaceSelector:
    matchNames:
      - default  # or the namespace where Jenkins runs
  endpoints:
  - port: http
    path: prometheus
    interval: 30s
