apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-force
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /prometheus
    scheme: http
    params:
      auth:
      - username: admin
      - password: admin123
    staticConfigs:
      - targets: ['jenkins.default.svc.cluster.local']
