apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/jenkins/.minikube/ca.crt   # <-- changed from Windows to Linux path here
    extensions:
    - extension:
        last-update: Fri, 20 Jun 2025 11:00:29 WAT
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://127.0.0.1:56006
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 20 Jun 2025 11:00:29 WAT
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/jenkins/.minikube/profiles/minikube/client.crt
    client-key: /home/jenkins/.minikube/profiles/minikube/client.key
    certificate-authority: /home/jenkins/.minikube/ca.crt
