apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /prometheus
  selector:
    matchLabels:
      app: jenkins
  namespaceSelector:
    matchNames:
    - jenkins
