apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Optional, or leave it out to let K8s choose
  selector:
    app: petclinic
